logic_axioms = {
    "Identity": "x = x",                        
    "Non-Contradiction": "¬(P ∧ ¬P)",           
    "Excluded Middle": "P ∨ ¬P",                
    "Modus Ponens": "If P and P -> Q, then Q",  
    "Double Negation": "¬¬P → P",               
    "Transitivity": "If P -> Q and Q -> R, then P -> R",  
    "Universal Instantiation": "∀x P(x) -> P(c)",    
    "Existential Generalization": "P(c) -> ∃x P(x)", 
    "Conjunction": "P ∧ Q -> P, P ∧ Q -> Q",         
    "Disjunction Introduction": "P -> P ∨ Q",        
    "Disjunction Elimination": "P ∨ Q, ¬P -> Q",     
    "Biconditional Introduction": "(P -> Q) ∧ (Q -> P) -> P ↔ Q",  
    "Biconditional Elimination": "P ↔ Q -> (P -> Q) ∧ (Q -> P)",   
    "Implication": "P -> Q is the same as ¬P ∨ Q",  
    "De Morgan's Laws": "¬(P ∧ Q) ↔ (¬P ∨ ¬Q)",     
    "Contrapositive": "P -> Q ↔ ¬Q -> ¬P",          
    "Negation Introduction": "If assuming P leads to a contradiction, then ¬P",  
    "Existential Instantiation": "∃x P(x) -> P(c)", 
    "Universal Generalization": "P(c) for arbitrary c -> ∀x P(x)", 
    "Hypothetical Syllogism": "If P -> Q and Q -> R, then P -> R",
    "Necessity": "□P → P",                       
    "Possibility": "P → ◇P",                   
    "Necessity Distribution": "□(P → Q) → (□P → □Q)",  
    "Possibility Distribution": "◇(P ∨ Q) ↔ (◇P ∨ ◇Q)"  
}

